repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v3.4.0
   hooks:
     - id: check-docstring-first
     - id: check-merge-conflict
     - id: trailing-whitespace
     - id: end-of-file-fixer
     - id: check-yaml
     - id: check-ast
     - id: pretty-format-json
     - id: requirements-txt-fixer
